$(document).ready(function(){
	$("#information").click(function(){
		$('#informationExpand').toggle("slow");
		});
	$("#events").click(function(){
		$('iframe').toggle("slow");
		});
	$("#active").click(function(){
		$('#form').toggle("slow");
		});
	$("#docs").click(function(){
		$('.frame').css('display','block');
	});
});